HPCC-27853 - Create confidence tests and key files for the Text Vectors bundle
hpcc-systems/TextVectors pull request #2
Opened 2022-06-27 17:42 UTC by NSel1727

- Create ecl and key folder
- Develop test code to create confidence tests calling functions from the Text Vectors bundle
- Create a key file for each test, displaying the passing output in XML format

2022-07-06 18:22 UTC, AttilaVamos requested changes
Some questions.

2022-07-06 18:22 UTC, AttilaVamos commented on ecl/SVTest2.ecl
> +OUTPUT(IF(isAscending(Vectors), 'Pass', 'Vectors are not sorted by text'), NAMED('Test2'));
Why it should be sorted?

2022-07-06 18:22 UTC, AttilaVamos commented on ecl/SVTest2.ecl
> +OUTPUT(IF(ClosestResult = '', 'Pass', ClosestResult), NAMED('Test4'));
It is failed on my 4 Thor slaves environment.  The content of the closest is:
```
<Dataset name='Closest'>
 <Row><id>4</id><text>HPCC-Systems Programming uses Java</text><closest><Item>HPCC-Systems programming uses ecl</Item></closest><similarity><Item>0.7633770704269409</Item></similarity></Row>
 <Row><id>1</id><text>The sky is orange</text><closest><Item>The [sky] is blue</Item></closest><similarity><Item>0.8569954633712769</Item></similarity></Row>
 <Row><id>2</id><text>The building has nine rooms</text><closest><Item>The house has four ^rooms</Item></closest><similarity><Item>0.6496321558952332</Item></similarity></Row>
 <Row><id>3</id><text>Goodbye everyone</text><closest><Item>Greetings everyone</Item></closest><similarity><Item>0.7006987929344177</Item></similarity></Row>
</Dataset>
```
I think it is a sorting issue again.

2022-07-06 18:22 UTC, AttilaVamos commented on ecl/UtilsTest.ecl
> +STRING GetResultInt(INTEGER Expected, INTEGER Result) := FUNCTION
I think it is a bit misleading function name. It suggests to me I will get and Int(eger) result. 
What if you call it as 'CheckIntegerResult(...)' or something similar.

2022-07-06 18:22 UTC, AttilaVamos commented on ecl/UtilsTest.ecl
> +STRING GetResultBool(BOOLEAN Expected, BOOLEAN Result) := FUNCTION
Same as above.

2022-07-06 18:22 UTC, AttilaVamos commented on ecl/UtilsTest.ecl
> +STRING GetResultSet(SET OF REAL Expected, SET OF REAL Result) := FUNCTION
Same as above.

2022-07-06 18:22 UTC, AttilaVamos commented on ecl/UtilsTest.ecl
> +STRING GetResultSet2(SET OF REAL Expected, SET OF REAL Result) := FUNCTION
Same as above.

2022-07-06 18:42 UTC, NSel1727 commented on ecl/SVTest2.ecl
> +OUTPUT(IF(ClosestResult = '', 'Pass', ClosestResult), NAMED('Test4'));
I added a sort line that sorts closest by id. Your result is technically correct, but the one with id of 4 comes first.

2022-07-07 14:05 UTC, AttilaVamos requested changes
Some comments and change requests.

2022-07-07 14:05 UTC, AttilaVamos commented on ecl/SVTest2.ecl
> +OUTPUT(IF(isAscending(Vectors), 'Pass', 'Vectors are not sorted by text'), NAMED('Test2'));
I don't know why do you think the content of the 'Vectors' is sorted by the 'text' field?

2022-07-07 14:05 UTC, AttilaVamos commented on ecl/SVTest2.ecl
> +SORT(Closest, id);
The SORT() is not doing its work in-place, therefore it OUTPUT() the sorted version of Closest, but the original DATASET remain unsorted.
You can do that:
```
_Closest := SV.ClosestSentences(Model, SimilarSentences);
Closest := SORT(_Closest, id);
```
or 
```
Closest := SORT(SV.ClosestSentences(Model, SimilarSentences), id);
```

2022-07-07 14:05 UTC, AttilaVamos commented on ecl/UtilsTest.ecl
> +IMPORT Int.svUtils AS Utils;
I think the 'Int' can be misleading and you can merge these two lines into one:
```
IMPORT TextVectors.internal.svUtils AS Utils;
```

2022-07-07 14:05 UTC, AttilaVamos commented on ecl/SVTest2.ecl
> +IMPORT TV.Types;
This doesn't work with Regression Test Engine. Use same approach as used in UtilsTest.ecl:
```
IMPORT TextVectors AS TV;
IMPORT TextVectors.Types as Types;
```

2022-07-07 14:05 UTC, AttilaVamos commented on ecl/WeightsTest2.ecl
> +IMPORT TV.Types;
As for SVTest2.ecl this doesn't work with Regression Test Engine. 
Use this:
```
IMPORT TextVectors.Types;
```

2022-07-07 14:05 UTC, AttilaVamos commented on ecl/WeightsTest2.ecl
> +IMPORT TV.internal AS int;
I think the name 'Int' is misleading and/or confusing.

2022-07-07 14:05 UTC, AttilaVamos commented on ecl/WeightsTest2.ecl
> +            break
This solution checks the order only on the first node and miss if any other is unordered.

2022-07-07 14:05 UTC, AttilaVamos commented on ecl/getNGramsTest.ecl
> +IMPORT TV.Types;
As for SVTest2.ecl this doesn't work with Regression Test Engine.
Use this:
```
IMPORT TextVectors.Types;
```

2022-07-07 14:05 UTC, AttilaVamos commented on ecl/key/SVTest2.xml
> + <Info><Source>user</Source><Message>Status: Epoch = 1, Progress = 100%, Loss = 0, minEpoch = 1, LR = 0.01, batchSize = 0</Message></Info>
The Regression Test Engine automatically removes these '<Info...' lines from the result, so please remove them from the key file as well.

2022-07-07 14:05 UTC, AttilaVamos commented on ecl/sent2WordListTest.ecl
> +IMPORT TV.Types;
As for SVTest2.ecl this doesn't work with Regression Test Engine.
Use this:
```
IMPORT TextVectors.Types;
```

2022-07-07 14:05 UTC, AttilaVamos commented on ecl/sent2WordListTest.ecl
> +IMPORT TV.internal AS int;
Misleading/confusing name 'Int'.

2022-07-07 14:05 UTC, AttilaVamos commented on ecl/sent2WordListTest.ecl
> +/*##############################################################################
I think the test case name is a bit misleading and/or confusing, because it 'sent' nothing. I feel the 'sentence2WordListTest.ecl' would be better.

2022-07-07 14:40 UTC, NSel1727 commented on ecl/WeightsTest2.ecl
> +            break
I believe that was done because all nodes have the same slices so as long as one is correct that means the others will be accurate as well.

2022-07-07 14:45 UTC, NSel1727 commented on ecl/SVTest2.ecl
> +OUTPUT(IF(isAscending(Vectors), 'Pass', 'Vectors are not sorted by text'), NAMED('Test2'));
Because it looks like that is a functionality of GetWordVectors.

2022-07-07 16:03 UTC, AttilaVamos commented on ecl/SVTest2.ecl
> +OUTPUT(IF(isAscending(Vectors), 'Pass', 'Vectors are not sorted by text'), NAMED('Test2'));
If I run it on a system with Thor and 1 Slave then it really seems sorted by 'text':
```
<Dataset name='Result 2'>
 <Row><wordid>3</wordid><text>has</text><occurs>1</occurs><pdisc>0.0</pdisc><vec> ... </vec></Row>
 <Row><wordid>2</wordid><text>house</text><occurs>1</occurs><pdisc>0.0</pdisc><vec> ... </vec></Row>
 <Row><wordid>4</wordid><text>rooms</text><occurs>1</occurs><pdisc>0.0</pdisc><vec> ... </vec></Row>
 <Row><wordid>1</wordid><text>the</text><occurs>1</occurs><pdisc>0.0</pdisc><vec> ... </vec></Row>
 <Row><wordid>5</wordid><text>zoo</text><occurs>1</occurs><pdisc>0.0</pdisc><vec></vec></Row>
```
However if I run it on a Thor with 4 Slaves, then the sequence is:
```
 <Row><wordid>1</wordid><text>the</text><occurs>1</occurs><pdisc>0.0</pdisc><vec> ... </vec></Row>
 <Row><wordid>3</wordid><text>has</text><occurs>1</occurs><pdisc>0.0</pdisc><vec> ... </vec></Row>
 <Row><wordid>2</wordid><text>house</text><occurs>1</occurs><pdisc>0.0</pdisc><vec> ... </vec></Row>
 <Row><wordid>4</wordid><text>rooms</text><occurs>1</occurs><pdisc>0.0</pdisc><vec> ... </vec></Row>
 <Row><wordid>5</wordid><text>zoo</text><occurs>1</occurs><pdisc>0.0</pdisc><vec></vec></Row>
 ```

2022-07-08 10:54 UTC, AttilaVamos approved these changes
All tests are passed with Regression Test Engine. It is OK by Automated Testing point of view.
I think it is ready to review by other guys.

2022-07-08 13:56 UTC, NSel1727 commented
@ghalliday @RogerDev When available please review my pull request.

2022-07-15 14:53 UTC, AttilaVamos requested changes
Some missing '\n' a wrong key file name and extra lines in key file.

2022-07-15 14:53 UTC, AttilaVamos commented on OBTTests/ecl/key/UtilsTest.xml
> +</Dataset>
Missing '\n' at the end.

2022-07-15 14:53 UTC, AttilaVamos commented on OBTTests/ecl/key/WeightsTest2.xml
> +<Result>
Remove those leading 2 lines.

2022-07-15 14:53 UTC, AttilaVamos commented on OBTTests/ecl/key/WeightsTest2.xml
> +</Result>
Remove this as well and don't forget to put '\n' at the end of last line.

2022-07-15 14:53 UTC, AttilaVamos commented on OBTTests/ecl/key/keyGetNGramsTest.xml
> +</Dataset>
Missing '\n' at the end.

2022-07-15 14:53 UTC, AttilaVamos commented on OBTTests/ecl/key/SVTest2.xml
> +</Dataset>
Missing '\n' at the end.

2022-07-15 14:53 UTC, AttilaVamos commented on OBTTests/ecl/getNGramsTest.ecl
> +OUTPUT(StringResultCheck(Expected4, Result4), NAMED('Test4'));
Missing '\n' at the end.

2022-07-15 14:53 UTC, AttilaVamos commented on OBTTests/ecl/WeightsTest2.ecl
> +OUTPUT(IF(Pass, 'Pass', 'Slices are not concatenated'), NAMED('Test5'));
Missing '\n' at the end.

2022-07-15 14:53 UTC, AttilaVamos commented on OBTTests/ecl/UtilsTest.ecl
> +                                                                                     //first indexes should be multiplied
Missing '\n' at the end.

2022-07-15 14:53 UTC, AttilaVamos commented on OBTTests/ecl/SVTest2.ecl
> +OUTPUT(IF(ClosestResult = '', 'Pass', ClosestResult), NAMED('Test3'));
Missing '\n' at the end.

2022-07-15 14:53 UTC, AttilaVamos commented on OBTTests/ecl/key/sentence2WordListTest.xml
> +</Dataset>
Missing '\n' at the end.

2022-07-15 14:53 UTC, AttilaVamos commented on OBTTests/ecl/sentence2WordListTest.ecl
> +OUTPUT(CheckResult(Expected3, wordList[3].words), NAMED('Test3'));
Missing '\n' at the end.

2022-07-15 14:53 UTC, AttilaVamos commented on OBTTests/ecl/key/keyGetNGramsTest.xml
> +<Dataset name='Test1'>
Wrong key file name.

2022-07-22 16:49 UTC, NSel1727 commented
@ghalliday When available, please review my pull request and determine if it is ready to be merged.

2022-11-02 16:38 UTC, AttilaVamos commented
@ghalliday please check and merge.

2022-11-11 10:42 UTC, merged